<?php
// $Id: og_profiles.module,v 1.1 2008/07/29 08:39:09 henrysearle Exp $

/**
 * @file
 * Support for configurable user profiles in groups.
 */

/**
 * Private field, content only available to privileged users.
 */
define('og_profiles_PRIVATE', 1);

/**
 * Public field, content shown on profile page but not used on member list pages.
 */
define('og_profiles_PUBLIC', 2);

/**
 * Public field, content shown on profile page and on member list pages.
 */
define('og_profiles_PUBLIC_LISTINGS', 3);

/**
 * Hidden profile field, only accessible by administrators, modules and themes.
 */
define('og_profiles_HIDDEN', 4);

/**
 * Implementation of hook_help().
 */
function og_profiles_help($path, $arg) {
  switch ($path) {
    case 'admin/help#og_profiles':
      $output = '<p>'. t('The profile module allows custom fields (such as country, full name, or age) to be defined and displayed in the <em>My Account</em> section. This permits users of a site to share more information about themselves, and can help community-based sites organize users around specific information.') .'</p>';
      $output .= '<p>'. t('The following types of fields can be added to a user profile:') .'</p>';
      $output .= '<ul><li>'. t('single-line textfield') .'</li>';
      $output .= '<li>'. t('multi-line textfield') .'</li>';
      $output .= '<li>'. t('checkbox') .'</li>';
      $output .= '<li>'. t('list selection') .'</li>';
      $output .= '<li>'. t('freeform list') .'</li>';
      $output .= '<li>'. t('URL') .'</li>';
      $output .= '<li>'. t('date') .'</li></ul>';
      $output .= '<p>'. t('For more information, see the online handbook entry for <a href="@profile">Profile module</a>.', array('@profile' => 'http://drupal.org/handbook/modules/profile/')) .'</p>';
      return $output;
    case 'admin/user/og_profiles':
      return '<p>'. t("This page displays a list of the existing custom profile fields to be displayed on the groups <em>Member</em> list. To provide structure, similar or related fields may be placed inside a category. To add a new category (or edit an existing one), edit a profile field and provide a new category name. To change the category of a field or the order of fields within a category, grab a drag-and-drop handle under the Title column and drag the field to a new location in the list. (Grab a handle by clicking and holding the mouse while hovering over a handle icon.) Remember that your changes will not be saved until you click the <em>Save configuration</em> button at the bottom of the page.") .'</p>';
  }
}

/**
 * Implementation of hook_theme().
 */
function og_profiles_theme() {
  return array(
    'og_profiles_block' => array(
      'arguments' => array('account' => NULL, 'fields' => array()),
      'template' => 'profile-block',
    ),
    'og_profiles_listing' => array(
      'arguments' => array('account' => NULL, 'fields' => array()),
      'template' => 'profile-listing',
    ),
    'og_profiles_wrapper' => array(
      'arguments' => array('content' => NULL),
      'template' => 'profile-wrapper',
    ),
    'og_profiles_admin_overview' => array(
      'arguments' => array('form' => NULL),
      'file' => 'og_profiles.admin.inc',
    )
  );
}

/**
 * Implementation of hook_menu().
 */
function og_profiles_menu() {
  $items['og/users/%/list'] = array(
    'title' => 'List Members',
    'page callback' => 'og_profiles_member_list',
    'page arguments' => array(2),
    'type' => MENU_LOCAL_TASK,
    'access callback' => 'user_is_logged_in',
    'access arguments' => array(2),
    'file' => 'og_profiles.pages.inc',
    'weight' => -1,
  );
  $items['node/%/%'] = array(
    //'title' =>user_load(arg(2))->name.' Profile',
    'page callback' => 'og_profiles_view_profile',
    'page arguments' => array(2),
    'access callback' => 'is_subscriber',
    'access arguments' => array(1),
    'type' => MENU_CALLBACK,
    'file' => 'og_profiles.pages.inc',
  );
  $items['node/%/profile/admin'] = array(
    'title' => 'Profile Fields',
    'description' => 'Create customizable fields for the users in your group.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('og_profiles_admin_overview', 1),
    'type' => MENU_LOCAL_TASK,
    'access callback' => 'is_group_admin',
    'access arguments' => array(1),
    'file' => 'og_profiles.admin.inc',
    'weight' => 3
  );
  $items['node/%/profile/admin/add'] = array(
    'title' => 'Add field',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('og_profiles_field_form'),
    'access callback' => 'is_group_admin',
    'access arguments' => array(1),
    'type' => MENU_CALLBACK,
    'file' => 'og_profiles.admin.inc',
  );
  $items['node/%/profile/admin/autocomplete/%'] = array(
    'title' => 'Profile category autocomplete',
    'page callback' => 'og_profiles_admin_settings_autocomplete',
    'page arguments' => array(5, 1),
    'access callback' => 'is_group_admin',
    'access arguments' => array(1),
    'type' => MENU_CALLBACK,
    'file' => 'og_profiles.admin.inc',
  );
  $items['node/%/profile/admin/edit/%'] = array(
    'title' => 'Edit field',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('og_profiles_field_form'),
    'access callback' => 'is_group_admin',
    'access arguments' => array(1),
    'type' => MENU_CALLBACK,
    'file' => 'og_profiles.admin.inc',
  );
  $items['node/%/profile/admin/delete/%'] = array(
    'title' => 'Delete field',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('og_profiles_field_delete'),
    'access callback' => 'is_group_admin',
    'access arguments' => array(1),
    'type' => MENU_CALLBACK,
    'file' => 'og_profiles.admin.inc',
  );
  $items['profile/autocomplete'] = array(
    'title' => 'Profile autocomplete',
    'page callback' => 'og_profiles_autocomplete',
    'access arguments' => array('access user profiles'),
    'type' => MENU_CALLBACK,
    'file' => 'og_profiles.pages.inc',
  );
  return $items;
}

function is_subscriber($g_id) {
  global $user;
  return (isset($user->og_groups[$g_id]));
}

function is_group_admin($g_id) {
  global $user;
  if (!user_access('administer organic groups')) {
    if (isset($user->og_groups[$g_id]['is_admin'])) {
      return $user->og_groups[$g_id]['is_admin'];
    }
    else {
      return FALSE;
    }
  }
  else {
    return TRUE;
  }
}

function og_profiles_form_alter(&$form, $form_state, $form_id) {
  switch ($form_id) {
    case 'og_confirm_subscribe' :
      global $user;
      // if the user is subscribing to a group
      // get the organic groups profile options
      $gid = $form['gid']['#value'];
      $form['fields'] = og_profiles_form_profile($form, $user, NULL, TRUE, $gid);

      // move the submit button to the bottom of the page
      $form['actions']['#weight'] = 10;

      // if the form has been submitted then save the profile information
      if ($form_state['post']['op'] == 'Join') {
        og_profiles_save_profile($form_state['post'], $user, NULL, TRUE, $gid);
      }
      break;

    case 'og_confirm_unsubscribe' :
      if ($form_state['post']['op'] == 'Remove') {
        // Delete all the profile values the user has in that group
        // Select the fields the user has in that group
        global $user;
        $uid = $user->uid;
        $gid = $form['group_node']['#value']->nid;

        $sql = 'SELECT fid FROM {og_profiles_fields} WHERE group_id = %d';
        $result = db_query($sql, $gid);
        while ($field_id = db_fetch_object($result)) {
          // Delete the profile values with the user id of the user being delete and the fields id of the fields in that group
          $sql = 'DELETE FROM {og_profiles_values} WHERE fid = %d AND uid = %d';
          db_query($sql, $field_id->fid, $uid);  
        }
      }
      break;

    case 'og_manage_form' :
      global $user;
      // if the user is managing their profile
      // get the profile form
      $gid = $form['gid']['#value'];
      $form['og_profiles_fields'] = og_profiles_form_profile($form, $user, NULL, FALSE, $gid);
      $form['op']['#weight'] = 10;
      
      if (isset($form_state['post']['op']) && $form_state['post']['op'] == 'Save') {
        // Bit of an odd way of getting the fields but I need to unset them so it doesn't intefere
        // with og.module og_manage_form_submit. This is the cause of the patch that needs to be applied
        og_profiles_save_profile($form['#parameters'][1]['post'], $user, NULL, FALSE, $gid);
        // I need to unset all values from $form_state['values'] here
      }
      break;
  }  
}

function og_profiles_submit($node) {
  echo 'here';
}

/**
 * Implementation of hook_block().
 */
function og_profiles_block($op = 'list', $delta = 0, $edit = array()) {

  if ($op == 'list') {
    $blocks[0]['info'] = t('Author information');
    $blocks[0]['cache'] = BLOCK_CACHE_PER_PAGE | BLOCK_CACHE_PER_ROLE;
    return $blocks;
  }
  else if ($op == 'configure' && $delta == 0) {
    // Compile a list of fields to show
    $fields = array();
    $result = db_query('SELECT name, title, weight, visibility FROM {og_profiles_fields} WHERE visibility IN (%d, %d) ORDER BY weight', og_profiles_PUBLIC, og_profiles_PUBLIC_LISTINGS);
    while ($record = db_fetch_object($result)) {
      $fields[$record->name] = check_plain($record->title);
    }
    $fields['user_profile'] = t('Link to full user profile');
    $form['og_profiles_block_author_fields'] = array('#type' => 'checkboxes',
      '#title' => t('Profile fields to display'),
      '#default_value' => variable_get('og_profiles_block_author_fields', array()),
      '#options' => $fields,
      '#description' => t('Select which profile fields you wish to display in the block. Only fields designated as public in the <a href="@profile-admin">profile field configuration</a> are available.', array('@profile-admin' => url('admin/user/profile'))),
    );
    return $form;
  }
  else if ($op == 'save' && $delta == 0) {
    variable_set('og_profiles_block_author_fields', $edit['og_profiles_block_author_fields']);
  }
  else if ($op == 'view') {
    if (user_access('access user profiles')) {
      $output = '';
      if ((arg(0) == 'node') && is_numeric(arg(1)) && (arg(2) == NULL)) {
        $node = node_load(arg(1));
        $account = user_load(array('uid' => $node->uid));

        if ($use_fields = variable_get('og_profiles_block_author_fields', array())) {
          // Compile a list of fields to show.
          $fields = array();
          $result = db_query('SELECT name, title, type, visibility, weight FROM {og_profiles_fields} WHERE visibility IN (%d, %d) ORDER BY weight', og_profiles_PUBLIC, og_profiles_PUBLIC_LISTINGS);
          while ($record = db_fetch_object($result)) {
            // Ensure that field is displayed only if it is among the defined block fields and, if it is private, the user has appropriate permissions.
            if (isset($use_fields[$record->name]) && $use_fields[$record->name]) {
              $fields[] = $record;
            }
          }
        }

        if (!empty($fields)) {
          $profile = _og_profiles_update_user_fields($fields, $account);
          $output .= theme('og_profiles_block', $account, $profile, TRUE);
        }

        if (isset($use_fields['user_profile']) && $use_fields['user_profile']) {
          $output .= '<div>'. l(t('View full user profile'), 'user/'. $account->uid) .'</div>';
        }
      }

      if ($output) {
        $block['subject'] = t('About %name', array('%name' => $account->name));
        $block['content'] = $output;
        return $block;
      }
    }
  }
}

/**
 * Implementation of hook_user().
 */
function og_profiles_user($type, &$edit, &$user, $category = NULL) {
  switch ($type) {/*
    case 'load':
      return og_profiles_load_profile($user);
    case 'register':
      return og_profiles_form_profile($edit, $user, $category, TRUE);
    case 'update':
      return og_profiles_save_profile($edit, $user, $category);
    case 'insert':
      return og_profiles_save_profile($edit, $user, $category, TRUE);
    case 'view':
      return og_profiles_view_profile($user);
    case 'form':
      return og_profiles_form_profile($edit, $user, $category);
    case 'validate':
      return og_profiles_validate_profile($edit, $category);
    case 'categories':
      return og_profiles_categories();*/
    case 'delete':
      db_query('DELETE FROM {og_profiles_values} WHERE uid = %d', $user->uid);
  }
} 

function og_profiles_load_profile(&$user) {
  $result = db_query('SELECT f.name, f.type, v.value FROM {og_profiles_fields} f INNER JOIN {og_profiles_values} v ON f.fid = v.fid WHERE uid = %d', $user->uid);
  while ($field = db_fetch_object($result)) {
    if (empty($user->{$field->name})) {
      $user->{$field->name} = _og_profiles_field_serialize($field->type) ? unserialize($field->value) : $field->value;
    }
  }
}

function og_profiles_save_profile(&$edit, &$user, $category, $register = FALSE, $group_id = null) {
  $result = _og_profiles_get_fields($category, $register, $group_id);
  while ($field = db_fetch_object($result)) {
    if (_og_profiles_field_serialize($field->type)) {
      $edit[$field->name] = serialize($edit[$field->name]);
    }
    //var_dump($edit);
    db_query("DELETE FROM {og_profiles_values} WHERE fid = %d AND uid = %d", $field->fid, $user->uid);
    db_query("INSERT INTO {og_profiles_values} (fid, uid, value) VALUES (%d, %d, '%s')", $field->fid, $user->uid, $edit[$field->name]);
    // Mark field as handled (prevents saving to user->data).
    unset($edit[$field->name]);
  }
}

function og_profiles_view_field($user, $field) {
  // Only allow browsing of private fields for admins, if browsing is enabled,
  // and if a user has permission to view profiles. Note that this check is
  // necessary because a user may always see their own profile.
  $browse = user_access('access user profiles')
          && (user_access('administer users') || $field->visibility != og_profiles_PRIVATE)
          && !empty($field->page);

  if (isset($user->{$field->name}) && $value = $user->{$field->name}) {
    switch ($field->type) {
      case 'textarea':
        return check_markup($value);
      case 'textfield':
      case 'selection':
        return $browse ? l($value, 'profile/'. $field->name .'/'. $value) : check_plain($value);
      case 'checkbox':
        return $browse ? l($field->title, 'profile/'. $field->name) : check_plain($field->title);
      case 'url':
        return '<a href="'. check_url($value) .'">'. check_plain($value) .'</a>';
      case 'date':
        $format = substr(variable_get('date_format_short', 'm/d/Y - H:i'), 0, 5);
        // Note: Avoid PHP's date() because it does not handle dates before
        // 1970 on Windows. This would make the date field useless for e.g.
        // birthdays.
        $replace = array(
          'd' => sprintf('%02d', $value['day']),
          'j' => $value['day'],
          'm' => sprintf('%02d', $value['month']),
          'M' => map_month($value['month']),
          'Y' => $value['year'],
          'H:i' => NULL,
          'g:ia' => NULL,
        );
        return strtr($format, $replace);
      case 'list':
        $values = split("[,\n\r]", $value);
        $fields = array();
        foreach ($values as $value) {
          if ($value = trim($value)) {
            $fields[] = $browse ? l($value, 'profile/'. $field->name .'/'. $value) : check_plain($value);
          }
        }
        return implode(', ', $fields);
    }
  }
}

function og_profiles_view_profile(&$user, $group_id = null) {
  if (!isset($group_id)) {
    $group_id = arg(1);
  }

  $current_user = $GLOBALS['user'];
  // Show private fields to administrators and people viewing their own account.
  if (is_group_admin($group_id) || $current_user->uid == $user) {
    $result = db_query('SELECT category, title, type, value FROM {og_profiles_fields} INNER JOIN {og_profiles_values} ON {og_profiles_fields}.fid = {og_profiles_values}.fid WHERE visibility <> %d AND group_id = %d AND uid = %d ORDER BY category, weight', og_profiles_HIDDEN, $group_id, $user);
  }
  else {
    $result = db_query('SELECT category, title, type, value FROM {og_profiles_fields} INNER JOIN {og_profiles_values} ON {og_profiles_fields}.fid = {og_profiles_values}.fid WHERE visibility <> %d AND visibility <> %d AND group_id = %d AND uid = %d ORDER BY category, weight', og_profiles_PRIVATE, og_profiles_HIDDEN, $group_id, $user);
  }

  $node = node_load($group_id);
    
  $categories = array();
  while ($field = db_fetch_object($result)) {
    $categories[$field->category][] = array(
      'category' => $field->category, 
      'title' => $field->title, 
      'value' => $field->value,
      'type'  => $field->type);
  }

  if (isset($categories)) {
  	// Don't define output as here is the first place we know there will be something outputed
    $fields = array();
    $output = '';
    foreach ($categories as $category) {
      $fields = $category;
      $output .= '<h3>'. t($category[0]['category']) .'</h3><blockquote>';
      foreach ($fields as $field) {
        $output .= '<h4>'. t($field['title']) .":</h4>\n";
        if ($field['type'] != 'checkbox')
          $output .= t($field['value']);
        else if ($field['value'] == 1)
          $output .= t('Yes');
        else
          $output .= t('No');
      $output .= "<br /><br />\n";
      }
      $output .= '</blockquote>';
    }
  }
  else
    $output .= t('There are no items to display');

  // if there is an output
  if (isset($output) && $output != '') {
  	drupal_set_title(ucwords(user_load($user)->name) .' profile for '. $node->title);
  	return $output;
  }
  else
    return NULL;
}

function _og_profiles_form_explanation($field) {
  $output = $field->explanation;

  if ($field->type == 'list') {
    $output .= ' '. t('Put each item on a separate line or separate them by commas. No HTML allowed.');
  }

  if ($field->visibility == og_profiles_PRIVATE) {
    $output .= ' '. t('The content of this field is kept private and will not be shown publicly.');
  }

  return $output;
}

// This adds to the Registration form
function og_profiles_form_profile($edit, $user, $category, $register = FALSE, $group_id = NULL) {
  if (is_numeric($group_id)) {
    $result = _og_profiles_get_fields($category, $register, $group_id);
    $weight = -10;
    $fields = array();
    while ($field = db_fetch_object($result)) {
      $sql = 'SELECT value FROM {og_profiles_values} LEFT JOIN {og_profiles_fields} ON {og_profiles_values}.fid = {og_profiles_fields}.fid WHERE group_id = %d AND uid = %d AND {og_profiles_values}.fid = %d';
      $current = db_fetch_object(db_query($sql, $group_id, $user->uid, $field->fid));
      $category = $field->category;
      if (!isset($fields[$category])) {
        $fields[$category] = array(
          '#type' => 'fieldset', 
          '#title' => check_plain($category),
          '#collapsible' => $register,
          '#weight' => $weight++);
      }
      $default_value = (isset($current->value)) ? $current->value : '';
      switch ($field->type) {
        case 'textfield':
        case 'url':
          $fields[$category][$field->name] = array('#type' => 'textfield',
            '#title' => check_plain($field->title),
            '#default_value' => $default_value,
            '#maxlength' => 255,
            '#description' => _og_profiles_form_explanation($field),
            '#required' => $field->required
          );
          if ($field->autocomplete) {
            $fields[$category][$field->name]['#autocomplete_path'] = "profile/autocomplete/". $field->fid;
          }
          break;
        case 'textarea':
          $fields[$category][$field->name] = array('#type' => 'textarea',
            '#title' => check_plain($field->title),
            '#default_value' => $default_value,
            '#description' => _og_profiles_form_explanation($field),
            '#required' => $field->required,
          );
          break;
        case 'list':
          $fields[$category][$field->name] = array('#type' => 'textarea',
            '#title' => check_plain($field->title),
            '#default_value' => $default_value,
            '#description' => _og_profiles_form_explanation($field),
            '#required' => $field->required,
          );
          break;
        case 'checkbox':
          $fields[$category][$field->name] = array('#type' => 'checkbox',
            '#title' => check_plain($field->title),
            '#default_value' => $default_value,
            '#description' => _og_profiles_form_explanation($field),
            '#required' => $field->required,
          );
          break;
        case 'selection':
          $options = $field->required ? array() : array('--');
          $lines = split("[,\n\r]", $field->options);
          foreach ($lines as $line) {
            if ($line = trim($line)) {
              $options[$line] = $line;
            }
          }
          $fields[$category][$field->name] = array('#type' => 'select',
            '#title' => check_plain($field->title),
            '#default_value' => $default_value,
            '#options' => $options,
            '#description' => _og_profiles_form_explanation($field),
            '#required' => $field->required,
          );
          break;
        case 'date':
          $fields[$category][$field->name] = array('#type' => 'date',
            '#title' => check_plain($field->title),
            '#default_value' => $default_value,
            '#description' => _og_profiles_form_explanation($field),
            '#required' => $field->required,
          );
          break;
      }
    }
    return $fields;
  }
}

/**
 * Helper function: update an array of user fields by calling og_profiles_view_field
 */
function _og_profiles_update_user_fields($fields, $account) {
  foreach ($fields as $key => $field) {
    $fields[$key]->value = og_profiles_view_field($account, $field);
  }
  return $fields;
}

function og_profiles_validate_profile($edit, $category) {
  $result = _og_profiles_get_fields($category);
  while ($field = db_fetch_object($result)) {
    if ($edit[$field->name]) {
      if ($field->type == 'url') {
        if (!valid_url($edit[$field->name], TRUE)) {
          form_set_error($field->name, t('The value provided for %field is not a valid URL.', array('%field' => $field->title)));
        }
      }
    }
    else if ($field->required && !user_access('administer users')) {
      form_set_error($field->name, t('The field %field is required.', array('%field' => $field->title)));
    }
  }

  return $edit;
}

function og_profiles_categories() {
  $result = db_query("SELECT DISTINCT(category) FROM {og_profiles_fields}");
  $data = array();
  while ($category = db_fetch_object($result)) {
    $data[] = array(
      'name' => $category->category,
      'title' => $category->category,
      'weight' => 3,
      'access callback' => 'og_profiles_category_access',
      'access arguments' => array(1, $category->category)
    );
  }
  return $data;
}

/**
 * Menu item access callback - check if a user has access to a profile category.
 */
function og_profiles_category_access($account, $category) {
  if (user_access('administer users') && $account->uid > 0) {
    return TRUE;
  }
  else {
    return user_edit_access($account) && db_result(db_query("SELECT COUNT(*) FROM {og_profiles_fields} WHERE category = '%s' AND visibility <> %d", $category, og_profiles_HIDDEN));
  }
}

/**
 * Process variables for profile-block.tpl.php.
 *
 * The $variables array contains the following arguments:
 * - $account
 * - $fields
 *
 * @see profile-block.tpl.php
 */
function template_preprocess_og_profiles_block(&$variables) {

  $variables['picture'] = theme('user_picture', $variables['account']);
  $variables['profile'] = array();
  // Supply filtered version of $fields that have values.
  foreach ($variables['fields'] as $field) {
    if ($field->value) {
      $variables['profile'][$field->name]->title = check_plain($field->title);
      $variables['profile'][$field->name]->value = $field->value;
      $variables['profile'][$field->name]->type = $field->type;
    }
  }

}

/**
 * Process variables for profile-listing.tpl.php.
 *
 * The $variables array contains the following arguments:
 * - $account
 * - $fields
 *
 * @see profile-listing.tpl.php
 */
function template_preprocess_og_profiles_listing(&$variables) {

  $variables['picture'] = theme('user_picture', $variables['account']);
  $variables['name'] = theme('username', $variables['account']);
  $variables['profile'] = array();
  // Supply filtered version of $fields that have values.
  foreach ($variables['fields'] as $field) {
    if ($field->value) {
      $variables['profile'][$field->name]->title = $field->title;
      $variables['profile'][$field->name]->value = $field->value;
      $variables['profile'][$field->name]->type = $field->type;
    }
  }

}

/**
 * Process variables for profile-wrapper.tpl.php.
 *
 * The $variables array contains the following arguments:
 * - $content
 *
 * @see profile-wrapper.tpl.php
 */
function template_preprocess_og_profiles_wrapper(&$variables) {
  $variables['current_field'] = '';
  if ($field = arg(1)) {
    $variables['current_field'] = $field;
    // Supply an alternate template suggestion based on the browsable field.
    $variables['template_files'][] = 'profile-wrapper-'. $field;
  }
}

function _og_profiles_field_types($type = NULL) {
  $types = array('textfield' => t('single-line textfield'),
                 'textarea' => t('multi-line textfield'),
                 'checkbox' => t('checkbox'),
                 'selection' => t('list selection'),
                 'list' => t('freeform list'),
                 'url' => t('URL'),
                 'date' => t('date'));
  return isset($type) ? $types[$type] : $types;
}

function _og_profiles_field_serialize($type = NULL) {
  return $type == 'date';
}

function _og_profiles_get_fields($category, $register = FALSE, $group_id = NULL) {
  $args = array();
  $sql = 'SELECT * FROM {og_profiles_fields} WHERE ';
  $filters = array();
  if ($register) {
    $filters[] = 'register = 1';
  }
  /* This is part of the old profiles module where fields are viewed and edited by catagory
   * we are not including this in this module at the moment but may implement in the future
  else {
    // Use LOWER('%s') instead of PHP's strtolower() to avoid UTF-8 conversion issues.
    $filters[] = "LOWER(category) = LOWER('%s')";
    $args[] = $category;
  }*/
  if (!user_access('administer users')) {
    $filters[] = 'visibility != %d';
    $args[] = og_profiles_HIDDEN;
  }
  if (isset($group_id)) { 
    $filters[] = 'group_id = %d';
    $args[] = $group_id;
  }
  $sql .= implode(' AND ', $filters);
  // if the group id is set add to sql and arguements
  $sql .= ' ORDER BY category, weight';
  return db_query($sql, $args);
}

