<?php
// $Id: addthis.module,v 1.13.2.8 2008/11/16 07:53:15 wesku Exp $

/**
 * @file
 * Stand alone module file to handle AddThis button integration
 */

/**
 * Implementation of hook_perm().
 */
function addthis_perm() {
  $perms[] = 'administer addthis';
  $perms[] = 'view addthis';
  return $perms;
}

/**
 * Implementation of hook_link().
 */
function addthis_link($type, $node=NULL, $teaser = FALSE) {
  $links = array();

  if ($type === 'node' && user_access('view addthis')) {
    if (($teaser && variable_get('addthis_display_in_teasers', '0')) ||
      (!$teaser && variable_get('addthis_display_in_links', '0'))) {
      $links['addthis'] = array(
          'title' => _addthis_create_button($node, $teaser),
          'html' => TRUE,
        );
    }
  }

  return $links;
}
/**
 * Implementation of hook_menu().
 */
function addthis_menu() {
  $items = array();

  $items['admin/settings/addthis'] = array(
    'title'            => t('AddThis'),
    'description'      => t('Set username and customize look and feel for <a href="http://www.addthis.com/">AddThis</a> button.'),
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('addthis_admin_settings'),
    'access arguments' => array('administer addthis'),
    'file'             => 'addthis.admin.inc',
  );

  return $items;
}

/**
 * Implementation of hook_block().
 */
function addthis_block($op = 'list', $delta = 0) {
  if ($op == 'list') {
    $blocks[0]['info'] = t('AddThis button');
    return $blocks;
  }
  else if ($op == 'view' && user_access('view addthis')) {
    $block['subject'] = t('AddThis');
    $block['content'] = _addthis_create_button();
    return $block;
  }
}

/**
 * Internal function to generate code for AddThis button
 *
 * @return
 *   String containing html code for the button
 */
function _addthis_create_button($node=NULL, $teaser = FALSE) {
  global $_addthis_counter;
  $_addthis_counter++;
  if ($_addthis_counter == 1) {
      drupal_add_css((drupal_get_path('module', 'addthis') .'/addthis.css'));
      drupal_add_js(sprintf('
	    addthis_pub = \'%s\';
	    addthis_logo = \'%s\';
	    addthis_logo_background = \'%s\';
	    addthis_logo_color = \'%s\';
	    addthis_brand = \'%s\';
	    addthis_options = \'%s\';
	',
        variable_get('addthis_username', 'my-username'),
        variable_get('addthis_logo', 'http://www.addthis.com/images/yourlogo.png'),
        variable_get('addthis_logo_background', 'EFEFFF'),
        variable_get('addthis_logo_color', '666699'),
        variable_get('addthis_brand', 'Your Site'),
        variable_get('addthis_options', 'favorites, email, digg, delicious, myspace, facebook, google, live, more')
      ), 'inline');
  }

  if (variable_get('addthis_dropdown_disabled', '0')) {
    return ( sprintf('
      <div class="addthis"><a href="http://www.addthis.com/bookmark.php"
        onclick="addthis_url   = location.href; addthis_title = document.title; return addthis_click(this);">
      <img src="%s" width="%d" height="%d" %s /></a></div>
      ',
      variable_get('addthis_image', 'http://s9.addthis.com/button1-share.gif'),
      variable_get('addthis_image_width', '125'),
      variable_get('addthis_image_height', '16'),
      variable_get('addthis_image_attributes', 'alt=""')
    ));
  }
  else {
    return ( sprintf('
      <div class="addthis"><a href="http://www.addthis.com/bookmark.php"
        onmouseover="return addthis_open(this, \'\', \'%s\', \'%s\')"
        onmouseout="addthis_close()"
        onclick="return addthis_sendto()"><img src="%s" width="%d" height="%d" %s /></a></div>
      <script type="text/javascript" src="http://s7.addthis.com/js/152/addthis_widget.js"></script>
      ',
      $teaser ? url('node/'. $node->nid, array('absolute' => 1) ) : '[URL]',
      $teaser ? addslashes($node->title) : '[TITLE]',
      variable_get('addthis_image', 'http://s9.addthis.com/button1-share.gif'),
      variable_get('addthis_image_width', '125'),
      variable_get('addthis_image_height', '16'),
      variable_get('addthis_image_attributes', 'alt=""')
    ));
  }
}
