<?php
// $Id: facebook_stream.module,v 1.2 2009/06/10 14:29:36 prajwala Exp $

/**
 *@file
 * Using facebook stream api, display the facebook stream in a block
 *
 * This module provides folloowing functionality
 * 1. Ask the users to give permission to get the stream
 * 2. If the user give permissions it display the stream
 * 3. Provides configurations to display number of feeds in the block at user/%user/fbstreamconnect
 * 4. Provides configurations whether to display comments for the feed item or not.
 * 5. Provides configurations to filter the feeds by facebook filter.
 */

/**
 * Implementation of hook_menu().
 */
function facebook_stream_menu() {
  $items['user/%user/fbstreamconnect'] = array(
    'title' => t('Facebook Stream'),
    "description" => t("Change Dashboard of users."),
    "page callback" => "drupal_get_form",
    'page arguments' => array('fb_stream_config_form'),
    'access callback' => 'user_edit_access',
    'access arguments' => array(1),
    'type' => MENU_LOCAL_TASK,
  );
  
  $items['fbstream/get/post/comments'] = array(
    'title' => t('Facebook Stream post comments'),
    "page callback" => "fb_stream_get_post_comments",
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  
  $items['fbstream/get/post/likes'] = array(
    'title' => t('Facebook Stream post likes'),
    "page callback" => "fb_stream_get_post_likes",
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  
  $items['fbstream/get'] = array(
    'title' => t('Facebook Stream post likes'),
    "page callback" => "fb_stream_get",
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  
  return $items; 
}

/**
 * Implementation of hook_theme()
 * registering themes
 */
function facebook_stream_theme() {
  return array(
    'posts_display' => array(
      'arguments' => array('stream' => NULL),
      'template' => 'posts_display', 
      ),
    'comments_display' => array(
      'arguments' => array('comments' => NULL),
      'template' => 'comments_display',
      ),
    'likes_display' => array(
      'arguments' => array('friends' => NULL),
      'template' => 'likes_display',      
      ),
    );
}


/**
 * Defination of stream configuration form
 * 
 * @ingroup forms
 * @see fb_stream_config_form_validate
 * @see fb_stream_config_form_submit
 */
function fb_stream_config_form() {
  global $user;
  $data = unserialize($user->data);
  $form['count'] = array(
    '#type' => 'textfield',
    '#title' => t('No of Items to display'),
    '#default_value' => $data['fbstream_user'] ? $data['fbstream_user'] : 5 ,
    '#description' => t('NO of Feeds to display on the block.'),
    '#required' => TRUE,
    );
  $form['submit'] = array('#type' => 'submit', '#value' => t('Save'));
  return $form;
}

/**
 * validation for the stream configuration form
 *
 * @see fb_stream_config_form
 * @see fb_stream_config_form_submit
 *
 * @param $form
 *  The form containing form values
 * @param $form_state
 *
 * @return null
 *  If there is any validation error the it set the error message
 */
function fb_stream_config_form_validate($form, &$form_state) {
  if (!is_numeric($_POST['count'])) {
    form_set_error('', t('Value must me numeric'));
  }
}


/**
 * Form submit of stream configurations
 *
 * This function stores the stream configurations
 *
 * @see fb_stream_config_form
 * @see fb_stream_config_form_validate
 * @param $form
 *  The form containing form values
 * @param $form_state
 *
 * @return null
 *
 */
function fb_stream_config_form_submit($form, &$form_state) {
  global $user;
  if ($user) {
    $array = array('fbstream_user' => $form_state['values']['count']);
    $data = unserialize($user->data);
    $result_array = array_merge($data, $array);
    db_query("update {users} set data = '%s' where uid=%d", serialize($result_array), $user->uid);
 }
}

/**
 * Implementation of hook_block()
 */
function facebook_stream_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
  case 'list':
    $blocks[0]['info'] = t('Facebook Stream');
    return $blocks;
  case 'view':
    $block = array();
    switch ($delta) {
    case 0:
      // check whether user logged into facebook through our application
      if (!$fbuid = fbconnect_get_fbuid()) {
        drupal_set_message(t('Your Facebook session has expired, try to reconnect'));
        break;
      }
      $block['subject'] = t('Facebook Stream');
      $block['content'] = _get_facebbok_stream();
      // dialog box to display the comments and likes
      $block['content'] .= '<div id="post_dialog" class="hide"></div>';
      return $block;
    }
  case 'configure':
    $form = array();
    if ($delta == 0) {
      $form['fbstream_block_post_display_more'] = array(
        '#type' => 'checkbox',
        '#title' => t('Display full post information'),
        '#description' => t('Display the full information of the facebook stream post'),
        '#default_value' => variable_get('fbstream_block_post_display_more', 1),
        );
      
      $form['fbstream_block_posts_update_time'] = array(
        '#type' => 'textfield',
        '#title' => t('Facebook stream posts update time in minutes'),
        '#description' => t('Facebook stream posts will updation time'),
        '#default_value' => variable_get('fbstream_block_posts_update_time', 2),
        );
    }
    return $form;
  case 'save':
    if ($delta == 0) {
      variable_set('fbstream_block_post_display_more', $edit['fbstream_block_post_display_more']);
      variable_set('fbstream_block_posts_update_time', $edit['fbstream_block_posts_update_time']);
    }
    
  }
}

/**
 * Get the facebook stream of the currently logged in user
 */
function _get_facebbok_stream() {
  global $user;
  drupal_add_css(drupal_get_path('module', 'facebook_stream') .'/facebook_stream.css', 'theme');
  drupal_add_js(drupal_get_path('module', 'facebook_stream') .'/facebook_stream.js');
  jquery_ui_add(array('ui.dialog'));  
  
  // facebbok client
  $fb = facebook_client();
  $fbuid = fbconnect_get_fbuid();  
  try {
    $perms = $fb->api_client->users_hasAppPermission('read_stream', $fbuid);
  }
  catch (FacebookRestClientException $e) {
    drupal_set_message(t('Your Facebook session has expired, try to reconnect'));
    return t('Your Facebook session has expired, try to reconnect');
  }
  //TODO: write a function for geting permissions
  // check whether user gave permission to our application to access the stream
  if ($fbuid && $perms) {
    
    // get how many feed items to display
    $data = unserialize($user->data);   
    $count = $data['fbstream_user'] ? $data['fbstream_user'] : 5 ;
    
    // get the stream
    $stream = $fb->api_client->stream_get('', '', '0', '0', $count, '');
    
    $confs = array(
      'fbstream_dispaly' => variable_get('fbstream_block_post_display_more', 1),
      'fbstream_update_time' => variable_get('fbstream_block_posts_update_time', 2)
      );
    drupal_add_js($confs, 'setting');
    return theme('posts_display', $stream);
    
  }
  else {
    // ask the user to give permissions for our application to access his stream
    return 'Set the permissions for the Application<input type="submit" value="Get Perm" class="form-submit" onclick="prompt_for_permissions(\'read_stream\');">';
  }
}

/**
 * Places the stream posts in the fbml tags by applying css
 * 
 * PRESENTLY WE ARE NOT USING THIS WAY TO DISPALY STREAM
 * @param $stream
 *  facebook stream array. which has the information of all posts in the stream
 */
function fbstream_full_display($stream) {
  $output =    '<fb:serverfbml style="width: 100%;">';
  $output .=   '  <script type="text/fbml">';
  $output .=   '     <fb:fbml>';
  $output .=   '        <fb:prompt-permission perms="read_stream">';
  $output .=   '            Grant permission for status updates ';
  $output .=   '        </fb:prompt-permission>';
  
  foreach ($stream['posts'] as $post) {
    $output .= '        <div >';
    $output .= '            <fb:wall>'; 
    $output .= '               <fb:wallpost uid='. $post['source_id'] .'>'; 
    $output .= '                  <div> '. $post['message'] .' </div>';
    $output .=  _post_attachments($post);
    $output .= '                  <div>';
    $output .= '                     <fb:date t='. $post['updated_time'] .' format="verbose" />';
    $output .= '                  </div>';
    $output .= '               </fb:wallpost>';
    $output .= '            </fb:wall>';
    $output .= '        </div>';
  }
  
  $output .=   '     </fb:fbml>';
  $output .=   '  </script>';
  $output .=   '</fb:serverfbml>';
  return $output;
}

/**
 * Gets user information from the stream profiles array
 * 
 * @param $profiles
 *  Profiles array came in the stream.get response
 * @param $uid
 *  The information need to get from profiles array
 */
function _get_user_info($profiles, $uid) {
  foreach ($profiles as $profile) {
    if ($profile['id'] == $uid) {
      return $profile;
    }
  }
}

/**
 * Places the attachements of a post in a html.
 * @pram $post
 *   Stream post contains the information of the post
 * @return $output
 *   The html content of the post attachments information
 */
function _post_attachments($post) {
  // return empty string if attachment does not exist
  if (!isset($post['attachment']['media']) && !is_array($post['attachment']['media'])) {
    return '';
  }
  $output = '';
  foreach ($post['attachment']['media'] as $attach) {
    switch ($attach['type']) {
    case 'video':
      $output .= "<fb:flv src=$post[href] title='my movie' height='100' salign='r' img=$attach[src] scale='showall' />";
      break;
    case 'link':
      $output .= "<a href=$attach[href]><img src=$attach[src] height='100' width='100' /></a>";
      break;
    }
  }
  $output .= "<div>". $post['attachment']['description'] ."</div>";
  return $output;
}


/**
 * Convert the time duration into readable way like 2hours, 3minute etc..
 * 
 * @param $seconds
 *  timestamp which needs to convert into readable way
 * @param $use
 *  The y,M,w,d,h,m,s etc characters which needs to use
 * @param $zeros
 *  Count leading zeeros or not
 */
function time_duration($seconds, $use = NULL, $zeros = FALSE) {
  // Define time periods
  $periods = array(
    'years'     => 31556926,
    'Months'    => 2629743,
    'weeks'     => 604800,
    'days'      => 86400,
    'hours'     => 3600,
    'minutes'   => 60,
    'seconds'   => 1
  );
  
  // Break into periods
  $seconds = (float) $seconds;
  foreach ($periods as $period => $value) {
    if ($use && strpos($use, $period[0]) === FALSE) {
      continue;
    }
    $count = floor($seconds / $value);
    if ($count == 0 && !$zeros) {
      continue;
    }
    $array_key = strtolower($period);
    $segments[$array_key] = $count;
    $seconds = $seconds % $value;
  }
  
  // Build the string
  foreach ($segments as $key => $value) {
    $segment_name = substr($key, 0, -1);
    $segment = $value .' '. $segment_name;
    if ($value != 1) {
      $segment .= 's';
    }
    $array[] = $segment;
  }
  
  //   $str = implode(', ', $array);
  return $array[0];
}


function str_parse_url($str) {
  // regular expression for possible links formats 
  $regexp = '/((http\:\/\/(\w{3}\.)?|https\:\/\/(\w{3}\.)?|www\.|ftp\.|ftps\.){1}\S+\.\S+)/i';
  return preg_replace($regexp, '<a href="$1" target="_new">$1</a>', $str);
}



function fb_stream_get() {
  if (!$fbuid = fbconnect_get_fbuid()) {
    echo t('Your Facebook session has expired, try to reconnect');
    exit;
  }
  echo _get_facebbok_stream();
  exit;
}

/**
 * call back for the url fbstream/get/post/comments
 * 
 * Get the comments for the post and return the html of the comments
 */
function fb_stream_get_post_comments() {
  $post_id = $_POST['post_id'];
  $fb = facebook_client(); 
  $comments = $fb->api_client->stream_getComments($post_id);
  echo theme('comments_display', $comments);
  exit;
}

/**
 * call back for the url fbstream/get/post/likes
 * 
 * Get the likes for the post and return the html of the friends who likes this post
 */
function fb_stream_get_post_likes() {
  $post_id = $_POST['post_id'];
  $fb = facebook_client(); 
  $query = "SELECT likes FROM stream WHERE post_id='". $post_id ."'";
  $likes = $fb->api_client->fql_query($query);
  if (!$likes) {
    echo "There is no likes information for this post "; 
    exit;
  } 
  $likes = $likes[0]['likes'];
  $friends = Array();
  if (!empty($likes['sample'])) {
    $friends = array_merge($friends, $likes['sample']);
  }
  if (!empty($likes['friends'])) {
    $friends = array_merge($friends, $likes['friends']);
  }
  echo theme('likes_display', $friends);
  exit;
}
