<?php
// $Id: signup_confirm_email.module,v 1.1 2009/07/24 17:47:49 dww Exp $

/**
 * @file
 * The Signup confirm e-mail module is an add-on for the Signup module to
 * confirm a user's e-mail address when they sign up for content on the site.
 * It adds an extra field on the signup form, prepopulated with the user's
 * current e-mail address. If the user changes this field, they are presented
 * with a confirmation form, and if they accept, their e-mail address in their
 * user profile is updated accordingly.
 */


/**
 * Implement hook_menu().
 */
function signup_confirm_email_menu() {
  $items['node/%node/signup/confirm-email'] = array(
    'type' => MENU_CALLBACK,
    'description' => 'Confirmation page when changing e-mail during a signup.',
    'access arguments' => array('sign up for content'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('signup_confirm_email_confirm_form'),
    'file' => 'signup_confirm_email.inc',
  );
  return $items;
}

/**
 * Implement hook_form_alter().
 */
function signup_confirm_email_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'signup_form' || $form_id == 'signup_edit_form') {
    module_load_include('inc', 'signup_confirm_email', 'signup_confirm_email');
    signup_confirm_email_alter_signup_form(&$form, &$form_state, $form_id);
  }
}

