<?php

@(include_once('tarzan/tarzan.class.php')) or _creeper_tarzan_not_found();

//////////////////////////////// DRUPAL HOOK AND API FUNCTION /////////////////////////// 

/**
 * Implementation of hook_menu()
 */
function creeper_menu() {
  $items = array();

  $items['admin/settings/creeper/settings'] = array(
    'title' => 'Tarzan Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('creeper_admin_settings'),
    'description' => t('Configure Tarzan settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'creeper.admin.inc'
    );
  return $items;
}

/**
 * Provide an error message if the tarzan library is not found.
 */
 
 function _creeper_tarzan_not_found(){
    global $tarzancheckalready;
  if(!$tarzancheckalready) {
    $tarzancheckalready = TRUE;
    drupal_set_message(t('The <a href="@url" target="_blank">Tarzan PHP library</a> was not found. Please install it into %creeperdir.', array('@url' => 'http://tarzan-aws.com', '%creeperdir' => drupal_get_path('module', 'creeper') . '/tarzan')), 'error');
 }
 
 }