<?php

@(include_once('cloudfusion/cloudfusion.class.php')) or _creeper_cloudfusion_not_found();

//////////////////////////////// DRUPAL HOOK AND API FUNCTION /////////////////////////// 

/**
 * Implementation of hook_menu()
 */
function creeper_menu() {
  $items = array();

  $items['admin/settings/creeper'] = array(
    'title' => 'Cloudfusion Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('creeper_admin_settings'),
    'description' => t('Configure Cloudfusion settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'creeper.admin.inc'
    );
  return $items;
}

/**
 * Provide an error message if the cloudfusion library is not found.
 */
 
function _creeper_cloudfusion_not_found(){
  global $cloudfusioncheckalready;

  if(!$cloudfusioncheckalready) {
    $cloudfusioncheckalready = TRUE;
    drupal_set_message(t('The <a href="@url" target="_blank">Cloudfusion PHP library</a> was not found. Please install it into %creeperdir.', array('@url' => 'http://code.google.com/p/tarzan-aws/source/checkout', '%creeperdir' => drupal_get_path('module', 'creeper') . '/cloudfusion')), 'error');
  }
}